// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzw7cs6uuYWHpiPQBaGB3MbesU7NB6WRo',
    appId: '1:526108565067:web:f2d1675cd3bc07403bf7ce',
    messagingSenderId: '526108565067',
    projectId: 'fir-eticaret',
    authDomain: 'fir-eticaret.firebaseapp.com',
    storageBucket: 'fir-eticaret.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnizEY87nqhgAZlOmFPPvIPamGCEJ8sh4',
    appId: '1:526108565067:android:b728d9170a16424c3bf7ce',
    messagingSenderId: '526108565067',
    projectId: 'fir-eticaret',
    storageBucket: 'fir-eticaret.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXq7GOoazzrQpTdbaPx-d6Q_5SWjPWrmA',
    appId: '1:526108565067:ios:ce80f9fdabff805e3bf7ce',
    messagingSenderId: '526108565067',
    projectId: 'fir-eticaret',
    storageBucket: 'fir-eticaret.appspot.com',
    iosBundleId: 'com.example.firebaseGelismisEticaret',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXq7GOoazzrQpTdbaPx-d6Q_5SWjPWrmA',
    appId: '1:526108565067:ios:da001175f79435453bf7ce',
    messagingSenderId: '526108565067',
    projectId: 'fir-eticaret',
    storageBucket: 'fir-eticaret.appspot.com',
    iosBundleId: 'com.example.firebaseGelismisEticaret.RunnerTests',
  );
}
